completion: false
definitions: true
domains: []
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- .bundle/**/*
- tmp/**/*
- node_modules/**/*
- log/**/*
- public/**/*
- config/**/*
- Gemfile
- Gemfile.lock
- config/cloud-init/images/freebsd-12.2-amd64/**/*
- config/cloud-init/images/freebsd-13.0-amd64/**/*
- config/cloud-init/images/freebsd-14.0-amd64/**/*
- public/images/icons/flag_fra_tiny.png
- public/images/icons/flag_lax_tiny.png
- node_modules/@babel/core/node_modules/.bin/parser
- node_modules/@babel/core/node_modules/.bin/json5
- node_modules/@babel/core/node_modules/.bin/semver
- node_modules/@babel/generator/node_modules/.bin/jsesc
- node_modules/@babel/traverse/node_modules/.bin/parser
- node_modules/@babel/compat-data/node_modules/.bin/browserslist
- node_modules/@babel/compat-data/node_modules/.bin/semver
- node_modules/@babel/helper-compilation-targets/node_modules/.bin/browserslist
- node_modules/@babel/helper-compilation-targets/node_modules/.bin/semver
- node_modules/@babel/plugin-transform-runtime/node_modules/.bin/semver
- node_modules/@babel/preset-env/node_modules/.bin/browserslist
- node_modules/@babel/preset-env/node_modules/.bin/semver
- node_modules/@babel/template/node_modules/.bin/parser
- node_modules/@istanbuljs/load-nyc-config/node_modules/.bin/js-yaml
- node_modules/@jest/core/node_modules/.bin/jest-runtime
- node_modules/@jest/core/node_modules/.bin/rimraf
- node_modules/@jest/test-sequencer/node_modules/.bin/jest-runtime
- node_modules/acorn-globals/node_modules/.bin/acorn
- node_modules/autoprefixer/node_modules/.bin/browserslist
- node_modules/babel-loader/node_modules/.bin/mkdirp
- node_modules/babel-loader/node_modules/.bin/webpack
- node_modules/bonjour/node_modules/.bin/multicast-dns
- node_modules/@rails/webpacker/node_modules/.bin/js-yaml
- node_modules/@rails/webpacker/node_modules/.bin/node-sass
- node_modules/@rails/webpacker/node_modules/.bin/webpack
- node_modules/@rails/webpacker/node_modules/.bin/webpack-cli
- node_modules/@types/babel__template/node_modules/.bin/parser
- node_modules/@types/babel__core/node_modules/.bin/parser
- node_modules/cacache/node_modules/.bin/mkdirp
- node_modules/cacache/node_modules/.bin/rimraf
- node_modules/caniuse-api/node_modules/.bin/browserslist
- node_modules/compression-webpack-plugin/node_modules/.bin/webpack
- node_modules/copy-concurrently/node_modules/.bin/mkdirp
- node_modules/copy-concurrently/node_modules/.bin/rimraf
- node_modules/core-js-compat/node_modules/.bin/browserslist
- node_modules/core-js-compat/node_modules/.bin/semver
- node_modules/cosmiconfig/node_modules/.bin/js-yaml
- node_modules/create-hash/node_modules/.bin/sha.js
- node_modules/create-hmac/node_modules/.bin/sha.js
- node_modules/cross-spawn/node_modules/.bin/semver
- node_modules/cross-spawn/node_modules/.bin/which
- node_modules/css-loader/node_modules/.bin/cssesc
- node_modules/css-loader/node_modules/.bin/semver
- node_modules/css-loader/node_modules/.bin/webpack
- node_modules/del/node_modules/.bin/rimraf
- node_modules/diffie-hellman/node_modules/.bin/miller-rabin
- node_modules/enhanced-resolve/node_modules/memory-fs/node_modules/.bin/errno
- node_modules/escodegen/node_modules/.bin/esparse
- node_modules/escodegen/node_modules/.bin/esvalidate
- node_modules/file-loader/node_modules/loader-utils/node_modules/.bin/json5
- node_modules/file-loader/node_modules/.bin/webpack
- node_modules/find-cache-dir/node_modules/make-dir/node_modules/.bin/semver
- node_modules/fstream/node_modules/.bin/mkdirp
- node_modules/fstream/node_modules/.bin/rimraf
- node_modules/global-prefix/node_modules/.bin/which
- node_modules/http-signature/node_modules/.bin/sshpk-conv
- node_modules/http-signature/node_modules/.bin/sshpk-sign
- node_modules/http-signature/node_modules/.bin/sshpk-verify
- node_modules/invariant/node_modules/.bin/loose-envify
- node_modules/istanbul-lib-instrument/node_modules/.bin/semver
- node_modules/jest/node_modules/.bin/import-local-fixture
- node_modules/jest/node_modules/.bin/jest
- node_modules/jest-changed-files/node_modules/cross-spawn/node_modules/.bin/node-which
- node_modules/jest-cli/node_modules/.bin/import-local-fixture
- node_modules/jest-cli/node_modules/.bin/is-ci
- node_modules/jest-haste-map/node_modules/.bin/sane
- node_modules/jest-haste-map/node_modules/.bin/node-which
- node_modules/jest-jasmine2/node_modules/.bin/jest-runtime
- node_modules/jest-runner/node_modules/.bin/jest-runtime
- node_modules/jest-util/node_modules/.bin/is-ci
- node_modules/jest-snapshot/node_modules/.bin/semver
- node_modules/js-yaml/node_modules/.bin/esparse
- node_modules/js-yaml/node_modules/.bin/esvalidate
- node_modules/jsdom/node_modules/.bin/acorn
- node_modules/jsdom/node_modules/.bin/esgenerate
- node_modules/jsdom/node_modules/.bin/escodegen
- node_modules/loader-utils/node_modules/.bin/json5
- node_modules/make-dir/node_modules/.bin/semver
- node_modules/memory-fs/node_modules/.bin/errno
- node_modules/mini-css-extract-plugin/node_modules/.bin/webpack
- node_modules/move-concurrently/node_modules/.bin/mkdirp
- node_modules/move-concurrently/node_modules/.bin/rimraf
- node_modules/node-gyp/node_modules/.bin/mkdirp
- node_modules/node-gyp/node_modules/.bin/nopt
- node_modules/node-gyp/node_modules/.bin/rimraf
- node_modules/node-gyp/node_modules/.bin/semver
- node_modules/node-gyp/node_modules/.bin/which
- node_modules/node-notifier/node_modules/.bin/semver
- node_modules/node-notifier/node_modules/.bin/uuid
- node_modules/node-notifier/node_modules/.bin/node-which
- node_modules/node-sass/node_modules/cross-spawn/node_modules/.bin/which
- node_modules/node-sass/node_modules/.bin/in-publish
- node_modules/node-sass/node_modules/.bin/in-install
- node_modules/node-sass/node_modules/.bin/not-in-publish
- node_modules/node-sass/node_modules/.bin/not-in-install
- node_modules/node-sass/node_modules/.bin/mkdirp
- node_modules/node-sass/node_modules/.bin/node-gyp
- node_modules/node-sass/node_modules/.bin/sassgraph
- node_modules/normalize-package-data/node_modules/.bin/semver
- node_modules/optimize-css-assets-webpack-plugin/node_modules/.bin/webpack
- node_modules/pbkdf2/node_modules/.bin/sha.js
- node_modules/portfinder/node_modules/.bin/mkdirp
- node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/node_modules/.bin/cssesc
- node_modules/postcss-calc/node_modules/postcss-selector-parser/node_modules/.bin/cssesc
- node_modules/postcss-colormin/node_modules/.bin/browserslist
- node_modules/postcss-svgo/node_modules/.bin/svgo
- node_modules/postcss-merge-rules/node_modules/.bin/browserslist
- node_modules/postcss-minify-params/node_modules/.bin/browserslist
- node_modules/postcss-modules-local-by-default/node_modules/postcss-selector-parser/node_modules/.bin/cssesc
- node_modules/postcss-modules-scope/node_modules/postcss-selector-parser/node_modules/.bin/cssesc
- node_modules/postcss-normalize-unicode/node_modules/.bin/browserslist
- node_modules/postcss-preset-env/node_modules/.bin/autoprefixer
- node_modules/postcss-preset-env/node_modules/.bin/browserslist
- node_modules/postcss-preset-env/node_modules/.bin/css-blank-pseudo
- node_modules/postcss-preset-env/node_modules/.bin/css-has-pseudo
- node_modules/postcss-preset-env/node_modules/.bin/css-prefers-color-scheme
- node_modules/postcss-reduce-initial/node_modules/.bin/browserslist
- node_modules/postcss-selector-parser/node_modules/.bin/cssesc
- node_modules/redent/node_modules/.bin/strip-indent
- node_modules/regexpu-core/node_modules/.bin/regjsparser
- node_modules/regjsparser/node_modules/.bin/jsesc
- node_modules/request/node_modules/.bin/uuid
- node_modules/resolve-dir/node_modules/global-prefix/node_modules/.bin/which
- node_modules/sane/node_modules/.bin/watch
- node_modules/send/node_modules/.bin/mime
- node_modules/sass-loader/node_modules/.bin/semver
- node_modules/sass-loader/node_modules/.bin/webpack
- node_modules/sass-loader/node_modules/.bin/node-sass
- node_modules/sockjs/node_modules/.bin/uuid
- node_modules/source-map-resolve/node_modules/.bin/atob
- node_modules/stylehacks/node_modules/.bin/browserslist
- node_modules/style-loader/node_modules/loader-utils/node_modules/.bin/json5
- node_modules/style-loader/node_modules/.bin/webpack
- node_modules/svgo/node_modules/.bin/js-yaml
- node_modules/svgo/node_modules/.bin/mkdirp
- node_modules/terser-webpack-plugin/node_modules/.bin/terser
- node_modules/terser-webpack-plugin/node_modules/.bin/webpack
- node_modules/webpack/node_modules/cacache/node_modules/.bin/mkdirp
- node_modules/webpack/node_modules/cacache/node_modules/.bin/rimraf
- node_modules/webpack/node_modules/terser-webpack-plugin/node_modules/.bin/terser
- node_modules/webpack/node_modules/terser-webpack-plugin/node_modules/.bin/webpack
- node_modules/webpack/node_modules/.bin/acorn
- node_modules/webpack/node_modules/.bin/mkdirp
- node_modules/webpack-cli/node_modules/.bin/import-local-fixture
- node_modules/webpack-cli/node_modules/.bin/webpack
- node_modules/webpack-assets-manifest/node_modules/.bin/mkdirp
- node_modules/webpack-assets-manifest/node_modules/.bin/webpack
- node_modules/webpack-dev-middleware/node_modules/.bin/mime
- node_modules/webpack-dev-middleware/node_modules/.bin/mkdirp
- node_modules/webpack-dev-server/node_modules/.bin/ansi-html
- node_modules/webpack-dev-server/node_modules/.bin/import-local-fixture
- node_modules/webpack-dev-server/node_modules/.bin/semver
- node_modules/webpack-log/node_modules/.bin/uuid
- node_modules/worker-farm/node_modules/.bin/errno
- node_modules/.bin/parser
- node_modules/.bin/watch
- node_modules/.bin/rimraf
- node_modules/.bin/acorn
- node_modules/.bin/ansi-html
- node_modules/.bin/atob
- node_modules/.bin/autoprefixer
- node_modules/.bin/browserslist
- node_modules/.bin/semver
- node_modules/.bin/css-blank-pseudo
- node_modules/.bin/css-has-pseudo
- node_modules/.bin/css-prefers-color-scheme
- node_modules/.bin/cssesc
- node_modules/.bin/errno
- node_modules/.bin/esgenerate
- node_modules/.bin/escodegen
- node_modules/.bin/esparse
- node_modules/.bin/esvalidate
- node_modules/.bin/import-local-fixture
- node_modules/.bin/in-publish
- node_modules/.bin/in-install
- node_modules/.bin/not-in-publish
- node_modules/.bin/not-in-install
- node_modules/.bin/is-ci
- node_modules/.bin/node-which
- node_modules/.bin/jest-runtime
- node_modules/.bin/js-yaml
- node_modules/.bin/jsesc
- node_modules/.bin/loose-envify
- node_modules/.bin/miller-rabin
- node_modules/.bin/mime
- node_modules/.bin/mkdirp
- node_modules/.bin/multicast-dns
- node_modules/.bin/node-gyp
- node_modules/.bin/uuid
- node_modules/.bin/node-sass
- node_modules/.bin/nopt
- node_modules/.bin/regjsparser
- node_modules/.bin/sane
- node_modules/.bin/sassgraph
- node_modules/.bin/sha.js
- node_modules/.bin/sshpk-conv
- node_modules/.bin/sshpk-sign
- node_modules/.bin/sshpk-verify
- node_modules/.bin/strip-indent
- node_modules/.bin/svgo
- node_modules/.bin/terser
- node_modules/.bin/webpack
- node_modules/.bin/webpack-cli
- node_modules/.bin/json5
- node_modules/.bin/jest
- node_modules/.bin/webpack-dev-server
formatted: false
hover: false
include:
- lib/**/*.rb
- app/**/*.rb
- app/**/*.rake
- app/**/*.erb
- app/**/*.builder
- app/**/*.jbuilder
- app/**/*.rabl
- app/**/*.haml
- app/**/*.slim
max_files: 500
plugins: []
references: false
reporters: []
require: []
symbols: true
workspace_uri_filter: false
